export default [
	{ endpoint: 'login', httpMethod: 'get', login: false },
	{ endpoint: 'screenname-available', httpMethod: 'get', login: false },
	{ endpoint: 'account/create', httpMethod: 'post', login: false },
	{ endpoint: 'account/show', httpMethod: 'get', login: true, limitDuration: null, limitMax: null },
	{ endpoint: 'account/update-name', httpMethod: 'put', login: true, limitDuration: 1000 * 60 * 60 * 24, limitMax: 10 },
	{ endpoint: 'account/update-url', httpMethod: 'put', login: true, limitDuration: 1000 * 60 * 60 * 24, limitMax: 10 },
	{ endpoint: 'account/update-avatar', httpMethod: 'put', login: true, limitDuration: 1000 * 60 * 60 * 24, limitMax: 10 },
	{ endpoint: 'account/update-comment', httpMethod: 'put', login: true, limitDuration: 1000 * 60 * 60 * 24, limitMax: 10 },
	{ endpoint: 'notifications/show', httpMethod: 'get', login: true, limitDuration: null, limitMax: null },
	{ endpoint: 'notifications/timeline', httpMethod: 'get', login: true, limitDuration: null, limitMax: null },
	{ endpoint: 'notifications/unreads-count', httpMethod: 'get', login: true, limitDuration: null, limitMax: null },
	{ endpoint: 'users/show', httpMethod: 'get', login: false },
	{ endpoint: 'users/follow', httpMethod: 'post', login: true, limitDuration: 1000 * 60 * 60, limitMax: 100 },
	{ endpoint: 'users/unfollow', httpMethod: 'delete', login: true, limitDuration: 1000 * 60 * 60, limitMax: 100 },
	{ endpoint: 'users/followings', httpMethod: 'get', login: false },
	{ endpoint: 'users/followers', httpMethod: 'get', login: false },
	{ endpoint: 'users/recommendations', httpMethod: 'get', login: true, limitDuration: null, limitMax: null },
	{ endpoint: 'users/search', httpMethod: 'get', login: false },
	{ endpoint: 'posts/timeline', httpMethod: 'get', login: true, limitDuration: 1000 * 60 * 10, limitMax: 100 },
	{ endpoint: 'posts/user-timeline', httpMethod: 'get', login: false },
	{ endpoint: 'posts/mentions', httpMethod: 'get', login: true, limitDuration: 1000 * 60 * 10, limitMax: 100 },
	{ endpoint: 'posts/show', httpMethod: 'get', login: false },
	{ endpoint: 'posts/talk', httpMethod: 'get', login: false },
	{ endpoint: 'posts/replies', httpMethod: 'get', login: false },
	{ endpoint: 'posts/timeline-unreads-count', httpMethod: 'get', login: true, limitDuration: null, limitMax: null },
	{ endpoint: 'posts/mentions-unreads-count', httpMethod: 'get', login: true, limitDuration: null, limitMax: null },
	{ endpoint: 'posts/status', httpMethod: 'post', login: true, limitDuration: 1000 * 60 * 60, limitMax: 100 },
	{ endpoint: 'posts/photo', httpMethod: 'post', login: true, limitDuration: 1000 * 60 * 60, limitMax: 100 },
	{ endpoint: 'posts/like', httpMethod: 'post', login: true, limitDuration: 1000 * 60 * 60, limitMax: 100 },
	{ endpoint: 'posts/repost', httpMethod: 'post', login: true, limitDuration: 1000 * 60 * 60, limitMax: 30 },
	{ endpoint: 'album/files/upload', httpMethod: 'post', login: true, limitDuration: 1000 * 60 * 60, limitMax: 100, file: true },
	{ endpoint: 'album/files/show', httpMethod: 'get', login: true, limitDuration: null, limitMax: null },
	{ endpoint: 'album/files/list', httpMethod: 'get', login: true, limitDuration: null, limitMax: null },
	{ endpoint: 'album/files/move', httpMethod: 'put', login: true, limitDuration: null, limitMax: null },
	{ endpoint: 'album/files/rename', httpMethod: 'put', login: true, limitDuration: null, limitMax: null },
	{ endpoint: 'album/files/delete', httpMethod: 'delete', login: true, limitDuration: null, limitMax: null },
	{ endpoint: 'album/folders/create', httpMethod: 'post', login: true, limitDuration: 1000 * 60 * 60, limitMax: 50 },
	{ endpoint: 'album/folders/move', httpMethod: 'put', login: true, limitDuration: null, limitMax: null },
	{ endpoint: 'album/folders/rename', httpMethod: 'put', login: true, limitDuration: null, limitMax: null },
	{ endpoint: 'hashtags/search', httpMethod: 'get', login: false }
]
